name: build wrench
on: 
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore solution
        run: dotnet restore "./Wrench/App/App.csproj" 
     
      - name: Build solution
        run: dotnet build "./Wrench/App/App.csproj"

      - name: Run tests
        run: dotnet test "./Wrench/Test/Test.csproj" -c Information --no-build --no-restore


  build-and-publish-docker:
    needs: build
    name: 'build and publish docker'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: list dict
        run: ls

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: wrenchapps/wrench:latest, wrenchapps/wrench:${{ github.run_number }}